services:
  - type: web
    name: science-conf-server
    runtime: node
    plan: free
    region: frankfurt
    rootDir: apps/server
    buildCommand: npm install
    startCommand: npx tsx src/index.ts
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
